# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - partyklinest-backend

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://partyklinest-backend.azurewebsites.net/
        username: ${{ secrets.AzureAppService_ContainerUsername_b00aee85f7f9415788e825fdd61d330a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_91d3f2fec5ab4965902cf1a5818ebfae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: partyklinest-backend.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_b00aee85f7f9415788e825fdd61d330a }}/appsvc/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'partyklinest-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad64cc5b3d044fb68c8d9d22aec55e50 }}
        images: 'partyklinest-backend.azurewebsites.net/${{ secrets.AzureAppService_ContainerUsername_b00aee85f7f9415788e825fdd61d330a }}/appsvc/backend:${{ github.sha }}'