name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  
  backend-build:
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    environment: development 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backend:$(date +%s)
